changelog:
  categories:
    - title: '🚀 Features'
      labels:
        - 'feature'
        - 'enhancement'
    - title: '🐛 Fixes'
      labels:
        - 'bug'
        - 'fix'
        - 'security'
    - title: '🏠 Improvements'
      labels:
        - 'improvement'
        - 'refactor'
        - 'ui'
    - title: '📦 Dependencies'
      labels:
        - 'dependencies'
    - title: '📖 Documentation'
      labels:
        - 'documentation'
    - title: '🏠 Maintenance'
      labels:
        - 'chore'
        - 'maintenance'
  exclude:
    labels:
      - 'ignore'
    authors:
      - 'octocat'
